plugins:
  - [
      "@semantic-release/commit-analyzer",
      {
        "releaseRules": [
          { "type": "chore", "scope": "deps", "release": "patch" },
          { "type": "chore", "scope": "dependencies", "release": "patch" },
          { "type": "refactor", "release": "patch" },
          { "type": "style", "release": "patch" }
        ]
      }
    ]
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - [
      "@semantic-release/exec",
      {
        prepareCmd: "sed -i 's/var Version = \".*\"/var Version = \"${nextRelease.version}\"/' cmd/vandyke/main.go"
      }
    ]
  - [
      "@semantic-release/git",
      {
        message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        assets: ["CHANGELOG.md", "cmd/vandyke/main.go"]
      }
    ]
  - "@semantic-release/github"

branches:
  - main
