#!/usr/bin/env python3
"""Fetch self-hosted web fonts (Fraunces + Instrument Sans, Latin subsets) from Google Fonts.

Downloads woff2 files into internal/web/static/fonts/ and writes fonts.css next to them
with local URLs, preserving unicode-ranges so other subsets never download.
"""
import os
import re
import urllib.request

UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/126.0.0.0 Safari/537.36"
)
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "internal", "web", "static", "fonts")
KEEP_SUBSETS = ("latin", "latin-ext")

CSS_URLS = [
    "https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,300..900&display=swap",
    "https://fonts.googleapis.com/css2?family=Instrument+Sans:ital,wght@0,400..700;1,400..700&display=swap",
]

BLOCK_RE = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", re.DOTALL)
PROP_RE = re.compile(r"([\w-]+)\s*:\s*([^;]+);")


def fetch(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8")


def main() -> int:
    os.makedirs(OUT_DIR, exist_ok=True)
    css_out = [
        "/* Self-hosted fonts. Generated by scripts/fetch_fonts.py — do not edit by hand. */",
        "",
    ]
    seen: set[str] = set()

    for css_url in CSS_URLS:
        css = fetch(css_url)
        for subset, block in BLOCK_RE.findall(css):
            if subset not in KEEP_SUBSETS:
                continue
            props = {k: v.strip() for k, v in PROP_RE.findall(block)}
            family = props.get("font-family", "").strip().strip("'\"")
            style = props.get("font-style", "normal")
            weight = props.get("font-weight", "400")
            src = props.get("src", "")
            match = re.search(r"url\((https://[^)]+\.woff2)\)", src)
            if not family or not match:
                continue
            remote = match.group(1)
            slug = re.sub(r"[^a-z0-9]+", "-", family.lower()).strip("-")
            style_slug = "" if style == "normal" else f"-{style}"
            filename = f"{slug}{style_slug}-{subset}.woff2"
            if filename not in seen:
                data = urllib.request.urlopen(
                    urllib.request.Request(remote, headers={"User-Agent": UA}), timeout=60
                ).read()
                with open(os.path.join(OUT_DIR, filename), "wb") as fh:
                    fh.write(data)
                seen.add(filename)
                print(f"downloaded {filename} ({len(data)} bytes)")
            css_out.append("@font-face {")
            css_out.append(f'  font-family: "{family}";')
            css_out.append(f"  font-style: {style};")
            css_out.append(f"  font-weight: {weight};")
            css_out.append("  font-display: swap;")
            css_out.append(f"  src: url(\"{filename}\") format(\"woff2\");")
            if "unicode-range" in props:
                css_out.append(f"  unicode-range: {props['unicode-range']};")
            css_out.append("}")
            css_out.append("")

    with open(os.path.join(OUT_DIR, "fonts.css"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(css_out))
    print(f"wrote {len(seen)} font files + fonts.css")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
